### ISSUE TITLE
Completely open to SQL Injection

### ISSUE THREAD

**Issue by benjaminpaul** [openqubit/sails-js-pagination#1]
The code used to do your pagination is completely open to SQL injection as well as completely bypassing the waterline ORM.

I am not really sure what the point of this project is... you can provide much more reliable and much more secure pagination using the waterline ORM using skip() and take() functions.

Crazy.

**Comment by openqubit** [comment]
The aim was to get a small example working first. Avoiding the orm altogether was the major undoing which will be rectified soon .

**Comment by benjaminpaul** [comment]
pagination with Sails.JS is done in about 4 lines of code using the ORM using skip() and take(), its much smaller to do it correctly.

Avoiding the ORM is not the main issue, the SQL injection is.

**Comment by openqubit** [comment]
I will open source the sails version come January.

**Comment by benjaminpaul** [comment]
What for? It's not required. Pointless project.

**Comment by openqubit** [comment]
Kinda is. If you are looking for some good pagination for sails,you can write yours or wait for two weeks. I have something that does not deviate from the orm?. This project is just to demonstrate a ported pagination method borrowed from php.You may have noticed a php version of it somewhere. I am sorry it couldn't help you.

**Comment by benjaminpaul** [comment]
It is not that I need help with pagination, its very simple to roll your own based on what is already available in sails.js.

My point is that your PHP version and this version both have massive security flaws in them that need to be highlighted so that users don't expose their apps when using your code.

The code in both this project and the PHP version is extremely poor and should not be made available.

Why have you closed the issue? It has not been fixed.

**Comment by openqubit** [comment]
Calling it 'extremely poor' is a bit of a stretch after all the query method is available on waterline http://sailsjs.org/documentation/reference/waterline-orm/models/query

Further more,the code is meant as some sort of a guide to someone rolling out his/her own pagination especially those coming from php. If you are an advanced javascript coder,the code may seem mundane but they are those who will find it half interesting and worth their while,well,half their while.

I think i should add the disclaimer that the code is in no way or shape ready for production. Anyone with the imaginative wits of a sickly sloth will acknowledge this.
